name: ecmwf-open-data-jupyter
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterlab
  - ipywidgets
  - numpy
  - pandas
  - xarray
  - scipy
  - matplotlib
  - cartopy
  - shapely
  - pyproj
  - eccodes
  - requests
  - beautifulsoup4
  - metpy
  - pint
  - pip
  - pip:
      - ecmwf-opendata